### ISSUE TITLE
swift compiler error

### ISSUE THREAD

**Issue by mvayngrib** [iProov/ios#1]
i'm running xcode 8.3.2. Is this a known issue / is there a known workaround? Thanks!

```
Module compiled with Swift 3.0.2 cannot be imported in Swift 3.1: /Users/mv/Code/iproov-ios/WaterlooBank/Pods/iProov/iProov.framework/Modules/iProov.swiftmodule/arm64.swiftmodule
```

**Comment by jonathanellis** [comment]
Thanks for bringing this to our attention. We need to re-compile our framework for Swift 3.1.

I'll do this later on today for you and publish an update to the pod, unfortunately I don't think there's anything you can do your end for the moment (aside from using an older version of Xcode!)

**Comment by mvayngrib** [comment]
@jonathanellis thanks, let me know when you've updated it?

**Comment by jonathanellis** [comment]
Hi @mvayngrib can you try running a `pod update`. It should update iProov to v5.1.0 which has been compiled for Swift 3.1

Thanks for your patience on this! Let me know if you have any further issue.

**Comment by mvayngrib** [comment]
@jonathanellis thanks, that fixed it!

maybe this is the wrong place to ask, but do you have an example flow described somewhere for using the end result token for enrollment/verification?

**Comment by mvayngrib** [comment]
(i already have the iProov API endpoints documentation)

**Comment by jonathanellis** [comment]
Glad it's working! Let me know if any other problems.

That's a good question, I shall refer you to @SoftForge to help with that.

**Comment by SoftForge** [comment]
@mvayngrib we have documented a few different flows depending on the use case. If you can drop us an email with some more details on what you are doing, we can provide the appropriate documentation and support.

**Comment by dom-f** [comment]
@mvayngrib It would help if we gave you an email address :)   Please email support@iproov.com and  reference this issue
