### ISSUE TITLE
error when building for simulator

### ISSUE THREAD

**Issue by mvayngrib** [iProov/ios#2]
I don't need to use iProov in the simulator, but I don't want to remove it every time before using the simulator. 

![image](https://user-images.githubusercontent.com/83948/26934184-a85752e2-4c36-11e7-9179-e6704e0e36cb.png)

can you help please?

**Comment by Joe-Palmer** [comment]
This should now be resolved in SDK v5.1.2. Please reopen if you still have an issue.
