### ISSUE TITLE
Swift Version Error

### ISSUE THREAD

**Issue by tbehera** [iProov/ios#5]
![screenshot 2018-11-05 12 10 37](https://user-images.githubusercontent.com/18425898/48023869-d5984100-e0f3-11e8-8876-6c4968b72cc9.png)

**Comment by jonathanellis** [comment]
Please be advised that the latest Waterloo Bank version is shipping with an older SDK version which is incompatible with Xcode 10.1. Please run `pod update iProov` to update the pod to 6.2.0.
